name: Docker Build and Publish

on:
    push:
        branches:
            - master

jobs:
    build_and_push_arm64:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Packages
              run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

        - name: Build and push ARM64 image
          uses: docker/build-push-action@v3
          with:
              context: ./arm64
              file: ./arm64/Dockerfile.arm64
              push: true
              tags: ghcr.io/muhammadashouri/latestapps:latest-arm64

    build_and_push_amd64:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Packages
              run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

        - name: Build and push AMD64 image
          uses: docker/build-push-action@v3
          with:
              context: ./amd64
              file: ./amd64/Dockerfile.amd64
              push: true
              tags: ghcr.io/muhammadashouri/latestapps:latest-amd64
