name: Docker Build and Publish

on:
    push:
        branches:
            - master

jobs:
    build_and_push_arm64:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push ARM64 image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Dockerfile.arm64
                  platforms: linux/arm64
                  push: true
                  tags: ghcr.io/muhammadashouri/latestapps:latest-arm64

    build_and_push_amd64:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push AMD64 image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Dockerfile.amd64
                  platforms: linux/amd64
                  push: true
                  tags: ghcr.io/muhammadashouri/latestapps:latest-amd64
